service: pusher

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  push:
    handler: handler.push
    memorySize: 128
    description: Push an event via pusher
    events:
      - http:
          path: pusher
          method: post
